add members column
Quebecca/qc_info_rights pull request #1
Opened 2021-12-21 10:46 UTC by atigiti

2021-12-21 15:12 UTC, taieb123 requested changes

2021-12-21 15:12 UTC, taieb123 commented on Classes/Report/QcInfoRightsReport.php
> +use TYPO3\CMS\Core\Http\Response;
use Psr\Http\Message\ResponseInterface;

2021-12-21 15:12 UTC, taieb123 commented on Classes/Report/QcInfoRightsReport.php
> +     */
* @return ResponseInterface

2021-12-21 15:12 UTC, taieb123 commented on Classes/Report/QcInfoRightsReport.php
> +    public function showMembers(ServerRequestInterface $request): Response{
public function showMembers(ServerRequestInterface $request): ResponseInterface{

2021-12-21 15:12 UTC, taieb123 commented on Classes/Domain/Repository/BackendUserRepository.php
> +
/**
     * Missing php Docs and params
     * @param
     * @param 
     */

2021-12-21 15:12 UTC, taieb123 commented on Classes/Domain/Repository/BackendUserRepository.php
> +                $queryBuilder->expr()->eq('usergroup', $groupUid)
$queryBuilder->expr()->eq('usergroup', $queryBuilder->createNamedParameter($groupUid, \PDO::PARAM_INT))

*Utiliser "createNamedParameter" a chaque fois du besoin de passer un élément pour assurer que la requête et en sécurité d'après SQL injection

2021-12-21 15:12 UTC, taieb123 commented on Classes/Report/QcInfoRightsReport.php
> +        $members = $this->backendUserRepository->getGroupMembers($urlParam['groupUid'], $urlParam['selectedColumn']);
return new JsonResponse(['membres' => $members])
 
**tu peut changer les 3 derniers line avec le JsonResponse c'est par défauts statuts code 200

2021-12-21 15:12 UTC, taieb123 commented on Resources/Private/Language/Module/fr.locallang.xlf
> +			</trans-unit>
les champs username, realName, and mail sont par défaut traduit par BeUser Extension on peut l'utiliser sans le recréer 
\typo3\sysext\beuser\Resources\Private\Language\locallang.xlf

2021-12-21 15:12 UTC, taieb123 commented on Resources/Private/Language/Module/locallang.xlf
> +			</trans-unit>
La même pour le fichier du Lang français

2021-12-21 15:12 UTC, taieb123 commented on Resources/Private/Templates/Backend/BeUserGroupList.html
> +        <option value="username"><f:translate key="LLL:EXT:qc_info_rights/Resources/Private/Language/Module/locallang.xlf:column.option.username" /></option>
Change les champs username, realName, et mail on utilisons le BeUser extension
LLL:EXT:beuser/Resources/Private/Language/locallang.xlf:

2021-12-21 15:12 UTC, taieb123 commented on Resources/Public/Css/showMembers.css
> +
Utiliser les classes d-none, et d-block sans le recréer

2021-12-21 15:12 UTC, taieb123 commented on Resources/Public/Css/showMembers.css
> +
Utiliser class .list-unstyled et supprimer le fichier ccs et n'a pas le déclaré

2021-12-21 15:12 UTC, taieb123 commented on Classes/Report/QcInfoRightsReport.php
>          $pageRenderer->addCssFile(GeneralUtility::getFileAbsFileName('EXT:qc_info_rights/Resources/Public/Css/qcinforights.css'), 'stylesheet', 'all');
Pourquoi  tu créer un nouveau fichier tant que on a déjà?
d'après l'analyse on a pas besoin pour cette fichier, on peut utiliser des class prêt définies

2021-12-22 12:47 UTC, atigiti commented
le dernier PR traite les différents points mentionnés

2021-12-23 11:03 UTC, atigiti commented
le dernier commit est pour changer le code utiliser pour traduire les messages pour les valeur non fournis du base de données.

2021-12-30 09:11 UTC, taieb123 commented on Classes/Controller/BackendController.php
>  use TYPO3\CMS\Core\Http\Response;
s'il te plaît éliminer les class que non pas utiliser comme 
`use TYPO3\CMS\Core\Http\Response;`

2021-12-30 09:11 UTC, taieb123 commented on Resources/Public/JavaScript/ShowMembers.js
> +              else {
Change else if { } pas else { if {} } il faut le vérifier la condition avant de passer dans le "else" instruction,

2021-12-30 13:22 UTC, atigiti commented on Classes/Controller/BackendController.php
>  use TYPO3\CMS\Core\Http\Response;
dans ce dernier PR, j'ai verifié que tous les classes importé sans utilisées, aussi pour la classe Http\Response, elle est déjà utilisée dans la classe BackendController

2021-12-30 13:27 UTC, atigiti commented on Resources/Public/JavaScript/ShowMembers.js
> +              else {
c'est corrigé dans le dernier PR

2022-01-03 10:16 UTC, merged